### ISSUE TITLE
More data and search options

### ISSUE THREAD

**Issue by mspykerez** [micah686/VnManager#40] opened 2021-03-09 09:13 UTC
Hey! Thanks for this app, I was looking for something like it for ages now!

I’m trying out the latest release (1.0.6) and I see that some information are not being pulled from vndb.org like the ‘Original title’, ‘Developer’, ‘Publishers’, ‘Staff’, ‘platform’, etc, can such information be imported as well? What I miss the most is the ‘Releases’ information where it lists all the available releases for a game in different languages.

In addition I wish we could ‘search’ within the app for games based on the developer, language, tags and look for games with sequels or prequels that we don’t already have or even games that we have on the original language (ex: japanese) when a English version is available.

Some sort of Visual Novel recommendation/similar system perhaps based on vnstat.net would also be a nice thing to have.

Btw can you also provide a ‘portable’ (no installation required) version of the app ?

**Comment by micah686** [comment] 2021-03-10 01:34
Unfortunately, most of your features I won't do. I could probably put in the original title, developer, and publisher. Searching within the app by developer and stuff I won't implement, due to the complexity. Same with VN recommendations. And this app was designed to be not portable(due to the way things are encrypted), you wouldn't be able to even if you wanted to.

**Comment by micah686** [comment] 2021-03-20 04:09
Closing due to Won't fix.

**Closed by micah686** 2021-03-20 04:09 UTC
Labels: wontfix
